### ISSUE TITLE
Open dictionary seems to break show_if

### ISSUE THREAD

**Issue by EnigmaEmmy** [don-tnowe/godot-inspector-extender#11]
Opening or having a dictionary open when you select the node seems to prevent the show_if from working:

![Screen Recording 2024-08-31 213456](https://github.com/user-attachments/assets/58de70b9-5cee-4c47-b137-d2d66ce58a2b)

**Comment by don-tnowe** [comment]
Additional details:

- This affects hideable blocks above **and** below the Dictionary, including custom editors.
- This bug does not happen with https://github.com/don-tnowe/godot-dictionary-inspector. Create a problem, sell the solution? ¯\_(ツ)_/¯

**Comment by don-tnowe** [comment]
Found it. It's caused by `_can_handle` called when a Dictionary is opened, passing the created property editor. Normally, it would pass the edited object (*here this would be the dictionary*), so it's just unusual engine behaviour. Though I think I see the use case.

**HOWEVER**, it also breaks when a subresource is opened, and it is my own code's problem and I will fix it now.
