### ISSUE TITLE
somehow deletes nodes or crashes editor with some tool scripts

### ISSUE THREAD

**Issue by Lodugh** [don-tnowe/godot-inspector-extender#2]
You can replicate the issue in this demo: https://github.com/expressobits/inventory-system-demos
The bug happens when the plugin is enabled and I have an inventory node selected(in a scene that owns it) and I switch the scene tab.
Then sometimes the inventory node gets deleted or the editor just crashes. Theres no @@ used in the comments, so that shouldnt be an issue.
Only error that it spits out when it happens: 
editor/editor_data.cpp:1066 - Condition "!p_node->is_inside_tree()" is true

**Comment by don-tnowe** [comment]
So THAT what it was when I was working on my project. Thanks for finding a reproduction!

In my case it happened only with tool scripts. Seems to be the case with this demo too, other nodes aren't deleted.

Must be the workaround related to non-tool scripts not having certain properties/methods in the editor. I'll try to address this now

**Comment by don-tnowe** [comment]
Fixed, also please let me know if `@@resource_table` works with custom/addon classes.
