### ISSUE TITLE
show_if backwards in Godot 4.1.1 mono stable

### ISSUE THREAD

**Issue by Minoqi** [don-tnowe/godot-inspector-extender#5]
In Godot Stable 4.1.1 Mono, the _show_if()_ function works backwards. Instead of putting it above the variable, it only works if it's below it, so it takes the variable above it rather than below. Yet it still breaks if there's no variable underneath it. Had to move the _itemType_ variable underneath it otherwise Godot crashes (I assume causes an infinite loop)

![image](https://github.com/don-tnowe/godot-inspector-extender/assets/25846972/47c85abb-cf5f-4efa-ad04-dfeb60f10039)

Using VS Code editor

**Comment by Minoqi** [comment]
Messes up the order of the variables as well.

![image](https://github.com/don-tnowe/godot-inspector-extender/assets/25846972/795e6816-5e17-4835-8140-92330ff207b9)

**Comment by EthanGrahn** [comment]
I've been looking at this issue but haven't quite pinpointed where the fix would be. Here's what I've found so far.

The `@@show_if` only works if there is a table attribute above it. The example project only ever uses `@@show_if` with table attributes.
Example:
```gd
# @@dict_table(a : int, b : String, c : float, d : Vector2, e : Texture2D)
# @@scroll_box(256)
# @@show_if(var_enum == 1)
@export var var4 : Array[Dictionary]
```
If you remove the table attribute, or put `@@show_if` first, it will fail as this issue describes. The issue seems to be related to the incorrect object being passed into `_initialize`. When I fix the infinite loop, it hides the previous attribute as if there is an off-by-one error.

@don-tnowe if you have any ideas on where to look, I should be able to fix this pretty quickly.

**Comment by don-tnowe** [comment]
It seems that it was, in fact, coded to target the previous created property editor 🤔

https://github.com/don-tnowe/godot-inspector-extender/blob/09002246870d9919208631d23491c5a208dd5519/addons/inspector_extender/attributes/show_if.gd#L14-L20

Making it target the next editor requires a delay (*it's just not yet added at moment of creation*), but is possible:

```
	await get_tree().process_frame
	var cur_index := get_index() + 1
```

**HOWEVER**, this goes back to breaking tables, and possibly properties with other Inspector Extender attributes too. Another edit would be needed to fix this.

**Comment by EthanGrahn** [comment]
Ah, that makes sense. I was printing the tree structure while I was debugging and it only had the tree built for everything up to the `show_if`. I'll mess around and see if I can delay the `show_if` behavior _only_, rather than making a breaking change.

**Comment by EthanGrahn** [comment]
Alright, I got the delayed behavior working but it's not clean code and it breaks the tables. I'll do some reworking to see if I can get everything working properly.
